### ISSUE TITLE
It's my first time to use issues.

### ISSUE THREAD

**Issue by uchihatommy** [yiyuezhuo/Hex-Wargame-JavaScript#1]
Just have a test ,and try weather this way is better than e-mail ,lol.
BTW, may I use Chinese to chat with you ?

**Comment by yiyuezhuo** [comment]
Yes, use Chinese as in e-mail. Content on github issue can help more people, I think.

**Comment by uchihatommy** [comment]
那么刚才邮件上的问题：
1、这个项目的后端是用什么写的呢？又是如何连接的，因为我把你的项目下载以后，哪个varp方法出不来东西，我寻思可能没连接上服务端？
2、刚才我打包下载了你更新后的项目，其中p_1_shock和princess_battle这两个包会报错，错误代码如下：
Traceback (most recent call last):
  File "C:\Users\DELL\Documents\GitHub\Hex-Wargame-JavaScript\scenario\scenario_maker.py", line 306, in <module>
    model.parse(place=True)
  File "C:\Users\DELL\Documents\GitHub\Hex-Wargame-JavaScript\scenario\scenario_maker.py", line 291, in parse
    self.place_rewrite()
  File "C:\Users\DELL\Documents\GitHub\Hex-Wargame-JavaScript\scenario\scenario_maker.py", line 220, in place_rewrite
    unit=self.id_unit_dic[unit_id]
KeyError: 34

**Comment by yiyuezhuo** [comment]
1.没有后端，用jsonp就是为了本地直接打开*.html就可以正常读取剧本文件。读不出来的问题可能是我之前读取脚本的顺序不对，有时会读不出来。现在应该已经可以读出来了。
比如
`file:///E:/agent4/git_test/debug/Hex-Wargame-JavaScript-master/game.html?varp=scenario/Assaye.js`
可以直接换掉varp的值
`file:///E:/agent4/git_test/debug/Hex-Wargame-JavaScript-master/game.html?varp=scenario/output.js`
来读取新剧本。
2.我又下回来重试了一下，没有问题。你的命令行命令是什么？
